[package]
name = "wpifilter"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe       = "0.27"       # egui windowing
egui         = "0.27"       # immediate mode GUI
egui_plot    = "0.27"       # signal + spectrum plots
egui_node_graph2 = "0.7"
rustfft      = "6"          # FFT for spectrum analyzer
nalgebra     = "0.32"       # matrix math for filter design
rmp-serde    = "1"          # MessagePack for NT4
tokio        = { version = "1", features = ["full"] } # async NT4