//! ROS 2-native filter export.
//!
//! Generates, from a compiled biquad cascade:
//! - a YAML params file (`filter_chain.yaml`-style) carrying the raw biquad
//!   coefficients for the generated node,
//! - a standalone **rclcpp** (C++) filter node,
//! - a standalone **rclrs** (Rust) filter node,
//! - the raw coefficients as plain text.
//!
//! Both generated nodes subscribe to an input topic, run the cascade
//! sample-by-sample, and publish the result — drop them into a robot or
//! simulation workspace to reproduce what the GUI previewed. The exported
//! filter is always causal single-pass (zero-phase filtfilt is offline-only).

use crate::dsp::biquad::BiquadCascade;

pub struct ExportedCode {
    /// YAML params file for the generated node (raw biquad coefficients).
    pub yaml: String,
    /// Standalone rclcpp (C++) filter node.
    pub rclcpp: String,
    /// Standalone rclrs (Rust) filter node.
    pub rclrs: String,
    /// Raw coefficients, one section per line.
    pub coefficients: String,
}

pub fn export_cascade(cascade: &BiquadCascade, name: &str) -> ExportedCode {
    ExportedCode {
        yaml: to_yaml(cascade, name),
        rclcpp: to_rclcpp(cascade, name),
        rclrs: to_rclrs(cascade, name),
        coefficients: to_coefficients(cascade),
    }
}

fn section_rows(cascade: &BiquadCascade) -> Vec<String> {
    cascade
        .sections
        .iter()
        .map(|bq| {
            format!(
                "  - [{}, {}, {}, {}, {}]",
                bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
            )
        })
        .collect()
}

fn to_yaml(cascade: &BiquadCascade, name: &str) -> String {
    let mut s = String::new();
    s.push_str("# Generated by rosfilter — ROS 2 filter chain params\n");
    s.push_str(&format!("# Filter: {name}\n"));
    s.push_str("#\n");
    s.push_str("# Load with the generated rclcpp node:\n");
    s.push_str("#   ros2 run <your_package> filter_node --ros-args --params-file filter_chain.yaml\n");
    s.push_str("#\n");
    s.push_str("# Rows are one biquad section per line: [b0, b1, b2, a1, a2] (a0 normalized to 1),\n");
    s.push_str("# processed in order with the global gain applied first.\n");
    s.push_str("#\n");
    s.push_str("# Single-section lowpass/highpass designs can also be expressed with\n");
    s.push_str("# control_toolbox's FilterChain — see the commented example at the bottom.\n\n");
    s.push_str(&format!("{name}:\n"));
    s.push_str("  ros__parameters:\n");
    s.push_str("    input_topic: /raw/signal\n");
    s.push_str("    output_topic: /filtered/signal\n");
    s.push_str("    biquads:\n");
    for row in section_rows(cascade) {
        s.push_str(&format!("{row}\n"));
    }
    s.push_str(&format!("    gain: {}\n", cascade.gain));
    s.push_str("\n# control_toolbox equivalent for a single-section lowpass:\n");
    s.push_str("# filters:\n");
    s.push_str("#   - name: lowpass\n");
    s.push_str("#     type: filters/LowPassFilter\n");
    s.push_str("#     params:\n");
    s.push_str("#       freq: 10.0\n");
    s.push_str("#       sample_freq: 100.0\n");
    s
}

fn to_coefficients(cascade: &BiquadCascade) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "# {} biquad section(s),  global gain = {}\n",
        cascade.sections.len(),
        cascade.gain
    ));
    s.push_str("# columns: b0  b1  b2  a1  a2     (a0 normalized to 1)\n\n");
    for (i, bq) in cascade.sections.iter().enumerate() {
        s.push_str(&format!(
            "section[{i}]:  {:.12}  {:.12}  {:.12}  {:.12}  {:.12}\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s
}

fn to_rclcpp(cascade: &BiquadCascade, name: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by rosfilter — standalone rclcpp filter node\n");
    s.push_str(&format!("// Filter: {name}\n"));
    s.push_str("//\n");
    s.push_str("// subscribe → biquad cascade → publish. Drop into any rclcpp package:\n");
    s.push_str("//   add_executable(filter_node filter_node.cpp)\n");
    s.push_str("//   ament_target_dependencies(filter_node rclcpp std_msgs)\n");
    s.push_str("//\n");
    s.push_str("// Run:  ros2 run <your_package> filter_node\n");
    s.push_str("// (topics default to /raw/signal → /filtered/signal; remap with\n");
    s.push_str("//  --ros-args -r input:=/imu/data -r output:=/filtered)\n\n");
    s.push_str("#include <array>\n#include <memory>\n\n");
    s.push_str("#include \"rclcpp/rclcpp.hpp\"\n");
    s.push_str("#include \"std_msgs/msg/float64.hpp\"\n\n");
    s.push_str("// Direct Form II Transposed biquad — matches rosfilter's DSP exactly.\n");
    s.push_str("struct Biquad {\n");
    s.push_str("  double b0, b1, b2, a1, a2;\n");
    s.push_str("  double z1 = 0.0, z2 = 0.0;\n");
    s.push_str("  void reset() { z1 = z2 = 0.0; }\n");
    s.push_str("  double process(double x) {\n");
    s.push_str("    double y = b0 * x + z1;\n");
    s.push_str("    z1 = b1 * x - a1 * y + z2;\n");
    s.push_str("    z2 = b2 * x - a2 * y;\n");
    s.push_str("    return y;\n");
    s.push_str("  }\n");
    s.push_str("};\n\n");
    s.push_str("class FilterNode : public rclcpp::Node {\n");
    s.push_str("public:\n");
    s.push_str("  FilterNode() : Node(\"filter_node\") {\n");
    s.push_str("    // Cascade state; coefficients inlined below.\n");
    s.push_str(&format!("    cascade_.gain = {};\n", cascade.gain));
    s.push_str(&format!("    cascade_.sections = {{{{\n"));
    for bq in &cascade.sections {
        s.push_str(&format!(
            "      Biquad{{ {}, {}, {}, {}, {} }},\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s.push_str("    }};\n\n");
    s.push_str("    subscription_ = this->create_subscription<std_msgs::msg::Float64>(\n");
    s.push_str("      \"input\", rclcpp::SensorDataQoS(),\n");
    s.push_str("      [this](const std_msgs::msg::Float64::SharedPtr msg) {\n");
    s.push_str("        std_msgs::msg::Float64 out;\n");
    s.push_str("        out.data = cascade_.process(msg->data);\n");
    s.push_str("        publisher_->publish(out);\n");
    s.push_str("      });\n");
    s.push_str("    publisher_ = this->create_publisher<std_msgs::msg::Float64>(\n");
    s.push_str("      \"output\", rclcpp::SensorDataQoS());\n");
    s.push_str("    RCLCPP_INFO(this->get_logger(), \"filter_node up: input → output\");\n");
    s.push_str("  }\n\n");
    s.push_str("private:\n");
    s.push_str("  struct Cascade {\n");
    s.push_str("    double gain = 1.0;\n");
    s.push_str("    std::array<Biquad, 1> sections;\n");
    s.push_str("    void reset() { for (auto& b : sections) b.reset(); }\n");
    s.push_str("    double process(double x) {\n");
    s.push_str("      double y = x * gain;\n");
    s.push_str("      for (auto& b : sections) y = b.process(y);\n");
    s.push_str("      return y;\n");
    s.push_str("    }\n");
    s.push_str("  };\n");
    s.push_str("  Cascade cascade_;\n");
    s.push_str("  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr subscription_;\n");
    s.push_str("  rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr publisher_;\n");
    s.push_str("};\n\n");
    s.push_str("int main(int argc, char** argv) {\n");
    s.push_str("  rclcpp::init(argc, argv);\n");
    s.push_str("  rclcpp::spin(std::make_shared<FilterNode>());\n");
    s.push_str("  rclcpp::shutdown();\n");
    s.push_str("  return 0;\n");
    s.push_str("}\n");
    s
}

fn to_rclrs(cascade: &BiquadCascade, name: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by rosfilter — standalone rclrs filter node (ros2-rust)\n");
    s.push_str(&format!("// Filter: {name}\n"));
    s.push_str("//\n");
    s.push_str("// Requires a ROS 2 distro + the ros2-rust workspace (see README).\n");
    s.push_str("// Build with the `ros2` feature of this repo's workspace, or add this\n");
    s.push_str("// file to a colcon cargo package with rclrs + std_msgs dependencies.\n");
    s.push_str("// Run:  ros2 run <your_package> filter_node\n\n");
    s.push_str("use rclrs::*;\n\n");
    s.push_str("/// Direct Form II Transposed biquad — matches rosfilter's DSP exactly.\n");
    s.push_str("struct Biquad {\n");
    s.push_str("    b0: f64, b1: f64, b2: f64, a1: f64, a2: f64,\n");
    s.push_str("    z1: f64, z2: f64,\n");
    s.push_str("}\n\n");
    s.push_str("impl Biquad {\n");
    s.push_str("    fn new(b0: f64, b1: f64, b2: f64, a1: f64, a2: f64) -> Self {\n");
    s.push_str("        Self { b0, b1, b2, a1, a2, z1: 0.0, z2: 0.0 }\n");
    s.push_str("    }\n");
    s.push_str("    fn process(&mut self, x: f64) -> f64 {\n");
    s.push_str("        let y = self.b0 * x + self.z1;\n");
    s.push_str("        self.z1 = self.b1 * x - self.a1 * y + self.z2;\n");
    s.push_str("        self.z2 = self.b2 * x - self.a2 * y;\n");
    s.push_str("        y\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");
    s.push_str("fn main() -> Result<(), RclrsError> {\n");
    s.push_str("    let mut executor = Context::default_from_env()?.create_basic_executor();\n");
    s.push_str("    let node = executor.create_node(\"filter_node\")?;\n");
    s.push_str("    let publisher = node.create_publisher(\"output\")?;\n");
    s.push_str("    let mut cascade = Cascade::built();\n");
    s.push_str(&format!("    cascade.gain = {};\n", cascade.gain));
    s.push_str("    let _subscription = node.create_subscription::<std_msgs::msg::Float64, _>(\n");
    s.push_str("        \"input\",\n");
    s.push_str("        move |msg: std_msgs::msg::Float64| {\n");
    s.push_str("            let out = std_msgs::msg::Float64 { data: cascade.process(msg.data) };\n");
    s.push_str("            let _ = publisher.publish(out);\n");
    s.push_str("        },\n");
    s.push_str("    )?;\n");
    s.push_str("    executor.spin(SpinOptions::default());\n");
    s.push_str("    Ok(())\n");
    s.push_str("}\n\n");
    s.push_str("#[derive(Default)]\n");
    s.push_str("struct Cascade {\n");
    s.push_str("    gain: f64,\n");
    s.push_str("    sections: Vec<Biquad>,\n");
    s.push_str("}\n\n");
    s.push_str("impl Cascade {\n");
    s.push_str("    fn process(&mut self, x: f64) -> f64 {\n");
    s.push_str("        let mut y = x * self.gain;\n");
    s.push_str("        for b in &mut self.sections {\n");
    s.push_str("            y = b.process(y);\n");
    s.push_str("        }\n");
    s.push_str("        y\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");
    // The cascade is built with the coefficients, overriding the derive(Default)
    // zero values. `gain` gets overwritten again in main (kept for clarity).
    s.push_str("impl Cascade {\n");
    s.push_str("    fn built() -> Self {\n");
    s.push_str(&format!("        Self {{ gain: {}, sections: vec![\n", cascade.gain));
    for bq in &cascade.sections {
        s.push_str(&format!(
            "            Biquad::new({}, {}, {}, {}, {}),\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s.push_str("        ] }\n");
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsp::design;

    #[test]
    fn export_is_ros2_native() {
        // Smoke test: a 4th-order Butterworth produces YAML, an rclcpp node,
        // an rclrs node, and raw coefficients — and no FRC/WPILib artifacts.
        let cascade = design::butterworth_lowpass(1000.0, 100.0, 4);
        let exported = export_cascade(&cascade, "velocityFilter");
        assert!(exported.yaml.contains("ros__parameters"));
        assert!(exported.yaml.contains("biquads"));
        assert!(exported.rclcpp.contains("rclcpp::Node"));
        assert!(exported.rclcpp.contains("SensorDataQoS"));
        assert!(!exported.rclcpp.contains("frc::LinearFilter"));
        assert!(exported.rclrs.contains("rclrs"));
        assert!(exported.rclrs.contains("std_msgs::msg::Float64"));
        assert!(exported.coefficients.contains("section[0]"));
        // A 4th-order Butterworth = 2 biquad sections.
        assert_eq!(exported.yaml.matches("- [").count(), 2);
    }

    #[test]
    fn coefficients_preserve_full_precision() {
        let cascade = design::butterworth_lowpass(1000.0, 100.0, 4);
        let exported = export_cascade(&cascade, "f");
        // Rust's `{}` formatting on f64 is shortest-round-trip, so the
        // exported coefficient must parse back exactly.
        for bq in &cascade.sections {
            assert!(exported.rclcpp.contains(&format!("{}", bq.b0)));
            assert!(exported.rclcpp.contains(&format!("{}", bq.a2)));
        }
    }
}
