use crate::dsp::biquad::BiquadCascade;

pub struct ExportedCode {
    pub java:         String,
    pub cpp:          String,
    pub coefficients: String,
}

pub fn export_cascade(cascade: &BiquadCascade, name: &str) -> ExportedCode {
    ExportedCode {
        java:         to_java(cascade, name),
        cpp:          to_cpp(cascade, name),
        coefficients: to_coefficients(cascade),
    }
}

/// Single biquad → one LinearFilter.
/// Cascade → array of LinearFilters + a calculate() helper that chains them.
///
/// Why not collapse the cascade into one big LinearFilter with high-order
/// coefficients? Because polynomial convolution at order ≥ 4 is numerically
/// nasty — the same reason we use cascades internally. Better to give the
/// user multiple stable 2nd-order LinearFilters than one fragile 8th-order one.
fn to_java(cascade: &BiquadCascade, name: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by WPIFilter\n");
    s.push_str("import edu.wpi.first.math.filter.LinearFilter;\n\n");

    let single = cascade.sections.len() == 1 && (cascade.gain - 1.0).abs() < 1e-12;
    if single {
        let bq = &cascade.sections[0];
        s.push_str(&format!(
            "LinearFilter {name} = new LinearFilter(\n\
             \x20   new double[] {{ {:.10}, {:.10}, {:.10} }},  // ffGains: b0, b1, b2\n\
             \x20   new double[] {{ {:.10}, {:.10} }}            // fbGains: a1, a2\n\
             );\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
        return s;
    }

    s.push_str(&format!("// {}-section biquad cascade\n", cascade.sections.len()));
    s.push_str(&format!("LinearFilter[] {name} = new LinearFilter[] {{\n"));
    for bq in &cascade.sections {
        s.push_str(&format!(
            "    new LinearFilter(new double[] {{ {:.10}, {:.10}, {:.10} }}, \
             new double[] {{ {:.10}, {:.10} }}),\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s.push_str("};\n");
    s.push_str(&format!("static final double {name}Gain = {:.10};\n\n", cascade.gain));
    s.push_str(&format!(
        "double {name}Calculate(double input) {{\n\
         \x20   double y = input * {name}Gain;\n\
         \x20   for (LinearFilter f : {name}) y = f.calculate(y);\n\
         \x20   return y;\n\
         }}\n"
    ));
    s
}

fn to_cpp(cascade: &BiquadCascade, name: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by WPIFilter\n");
    s.push_str("#include <frc/filter/LinearFilter.h>\n#include <array>\n\n");

    let single = cascade.sections.len() == 1 && (cascade.gain - 1.0).abs() < 1e-12;
    if single {
        let bq = &cascade.sections[0];
        s.push_str(&format!(
            "frc::LinearFilter<double> {name}{{\n\
             \x20   {{ {:.10}, {:.10}, {:.10} }},\n\
             \x20   {{ {:.10}, {:.10} }}\n\
             }};\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
        return s;
    }

    s.push_str(&format!(
        "std::array<frc::LinearFilter<double>, {}> {name} = {{\n",
        cascade.sections.len()
    ));
    for bq in &cascade.sections {
        s.push_str(&format!(
            "    frc::LinearFilter<double>{{{{ {:.10}, {:.10}, {:.10} }}, \
             {{ {:.10}, {:.10} }}}},\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s.push_str("};\n");
    s.push_str(&format!("constexpr double {name}Gain = {:.10};\n\n", cascade.gain));
    s.push_str(&format!(
        "double {name}Calculate(double input) {{\n\
         \x20   double y = input * {name}Gain;\n\
         \x20   for (auto& f : {name}) y = f.Calculate(y);\n\
         \x20   return y;\n\
         }}\n"
    ));
    s
}

fn to_coefficients(cascade: &BiquadCascade) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "# {} biquad section(s),  global gain = {:.10}\n",
        cascade.sections.len(),
        cascade.gain
    ));
    s.push_str("# columns: b0  b1  b2  a1  a2     (a0 normalized to 1)\n\n");
    for (i, bq) in cascade.sections.iter().enumerate() {
        s.push_str(&format!(
            "section[{i}]:  {:.12}  {:.12}  {:.12}  {:.12}  {:.12}\n",
            bq.b0, bq.b1, bq.b2, bq.a1, bq.a2
        ));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsp::design;

    #[test]
    fn java_export_compiles_signature() {
        // Smoke test: a 4th-order Butterworth produces non-empty Java
        // mentioning the variable name and LinearFilter.
        let cascade = design::butterworth_lowpass(1000.0, 100.0, 4);
        let exported = export_cascade(&cascade, "velocityFilter");
        assert!(exported.java.contains("LinearFilter"));
        assert!(exported.java.contains("velocityFilter"));
        assert!(exported.cpp.contains("frc::LinearFilter"));
        assert!(exported.coefficients.contains("section[0]"));
    }
}